branches:
  only:
    - master

os:
  - linux
  - osx

language: rust

rust:
  - stable
  - beta
  - nightly

  # the earliest supported stable release; we depend upon
  #  * >= 1.32 for uniform module paths
  #  * >= 1.36 for MaybeUninit
  - 1.36.0

dist: xenial

addons:
  apt:
    packages:
      - libsodium-dev
  homebrew:
    packages:
      - libsodium
      - pkg-config
    update: true

env:
  global:
    - secure: "R0dzAI0lbNRFChOXNx56tLsGpaeY+hbn5kK3RG/E+CeKn4LmHYbCPjHLcwYgjFTxStEfaihq8Y/ZWezqwvsG9Y4nqFnS636E0yc9HRx8hkcRbVB1a4Bk4j+2uLYs3/OD3iDXNkp8vTrfWRvYu4O1HhBY3fAv5aMJnREMcNbTGeA="
    - CARGO_TERM_VERBOSE=true
    - RUSTFLAGS="-A unknown-lints -D warnings"
  matrix:
    - CARGOFLAGS=""
    - CARGOFLAGS="--release"

before_script:
  - rustup update
  - rustup component add clippy

script:
  - cargo build ${CARGOFLAGS}
  - cargo test  ${CARGOFLAGS}
  - >
    if [[ "${TRAVIS_RUST_VERSION}" = 'beta' || "${TRAVIS_RUST_VERSION}" = 'nightly' ]]; then
      cargo clippy ${CARGOFLAGS}
    fi

cache: cargo

matrix:
  fast_finish: true

  allow_failures:
    - rust: nightly

  # TODO: generate and upload docs
  include:
    - name: docs
      rust: stable
      os: linux
      dist: xenial

      env:
        - RUST_BACKTRACE=1

      before_script:
        - rustup update
        - cargo install cargo-update || echo "cargo-update already installed"
        - cargo install cargo-travis || echo "cargo-travis already installed"
        - cargo install-update -a

      script:
        - cargo doc --no-deps
        - cargo doc-upload --path "${TRAVIS_BRANCH}"

    - name: coverage
      rust: stable
      os: linux
      dist: xenial
      sudo: required

      addons:
        apt:
          packages:
            - libcurl4-openssl-dev
            - libdw-dev
            - libelf-dev
            - libiberty-dev
            - libsodium-dev
            - binutils-dev
            - cmake

      env:
        - COVERAGE=true

      before_script:
        - rustup update
        - cargo install cargo-update || echo "cargo-update already installed"
        - cargo install cargo-travis || echo "cargo-travis already installed"
        - cargo install-update -a

      script:
        - cargo coveralls --exclude-pattern "_ctest.rs,_ctest.c"
